---
# This playbook configures and deploys desktop computers, laptops, servers and
# virtual machines with ansible-pull.

- hosts: all
  tags: always
  become: true

  # Run pre-run tasks on all hosts.
  pre_tasks:

    - name: Update apt cache
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS',
        'elementary OS']

# Apply common configuration to all hosts.
- hosts: all
  tags: common
  become: true

  roles:
    - common

# # Configure and deploy personal computers and laptops.
# - hosts: pc
#   tags: pc
#   become: true

#   roles:
#     - pc

# # Apply power management tweaks to laptops.
# - hosts: laptop
#   tags: laptop
#   become: true

#   roles:
#     - laptop

# # Apply power management tweaks to laptops.
# - hosts: laptop
#   tags: laptop
#   become: true

#   roles:
#     - laptop

# # Configure and deploy servers.
# - hosts: server
#   tags: server
#   become: true
#   roles: server

# Run cleanup tasks on all hosts.
- hosts: all
  become: true
  tasks:

    - name: Remove unused packages
      apt: autoremove=yes

    - name: Clean package cache
      apt: autoclean=yes
