---
- name: Install apt-transport-https
  tags: always, common, apt-transport-https
  apt:
    name:
      - apt-transport-https
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS', 'elementary OS']

- name: Install software-properties-common
  tags: always, common, sofware-properties-common
  apt:
    name: software-properties-common
    install_recommends: no
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS', 'elementary OS']
