---
# This playbook applies the common configuration, packages and software to
# all hosts.

# Include variables for the host distribution
- include_vars: "{{ ansible_distribution
    | lower
    | replace('!', '')
    | replace(' ', '_') }}.yml"
  tags: always
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS', 'elementary OS']

- block:

  # Install common package depedencies
  - import_tasks: depedencies.yml

  # Install common packages
  - include_tasks: packages.yml

  # Install ufetch
  - include_tasks: software/ufetch.yml
    when: ufetch_package is defined
