---
# This playbook configures and deploys desktop and laptops.

# Include variables for the host distribution
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always
  when: ansible_distribution in [ 'Debian', 'Ubuntu', 'Pop!_OS', 'elementary OS' ]


